namespace PestControl.Api.Models
{
    /// <summary>
    /// Customer represents a person or business that has requested pest control services.
    /// This class maps directly to the "Customers" table in SQL Server.
    /// Each property corresponds to a column in that table.
    ///
    /// It is a plain data class — no logic, just properties and a constructor.
    /// These are sometimes called "POCO" classes (Plain Old C# Object).
    /// </summary>
    public class Customer
    {
        // Auto-generated by SQL Server — we pass 0 when creating a new customer
        public int Id { get; set; }

        // The customer's full name e.g. "John Smith"
        public string Name { get; set; }

        // Where the pest problem is located e.g. "14 Baker Street, London"
        public string Address { get; set; }

        // Contact number e.g. "07700900000"
        public string Phone { get; set; }

        // Email address e.g. "john@example.com"
        public string Email { get; set; }

        // What kind of property they have: "Residential", "Commercial", or "Industrial"
        public string PropertyType { get; set; }

        // Constructor — used to create a Customer object from SQL data or a form submission
        public Customer(int id, string name, string address, string phone, string email, string propertyType)
        {
            Id = id;
            Name = name;
            Address = address;
            Phone = phone;
            Email = email;
            PropertyType = propertyType;
        }
    }
}